version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:

  frontend:
    container_name: foodgram-frontend
    build: ./frontend
    command: cp -r /app/build/. /static/
    volumes:
      - ./frontend/:/app/result_build/

  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    container_name: foodgram-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    command: >
      sh -c "until nc -z $DB_HOST $DB_PORT; do
              echo 'Waiting for Postgresâ€¦';
              sleep 1;
            done &&
            python manage.py migrate &&
            python recipes/scripts/import_data.py &&
            python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static/
    ports:
      - "8000:8000"

  gateway:
    image: nginx:1.22.1
    container_name: foodgram-proxy
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./backend/docs/:/usr/share/nginx/html/api/docs:ro
      - static_volume:/etc/nginx/html/static/
      - media_volume:/etc/nginx/html/media/

    depends_on:
      - backend
      - frontend