version: '3.8'

volumes:
  pg_data:
  media_volume:
  static_volume:

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data


  backend:
    image: jurassicon/foodgram_backend
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static

  frontend:
    image: jurassicon/foodgram_frontend
    restart: always
    volumes:
      - static_volume:/app/static

  gateway:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/etc/nginx/html/static/
      - media_volume:/etc/nginx/html/media/
