version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    container_name: foodgram-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    command: >
      sh -c "until nc -z $DB_HOST $DB_PORT; do
              echo 'Waiting for Postgresâ€¦';
              sleep 1;
            done &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - media_volume:/media
      - static_volume:/staticfiles
    ports:
      - "8000:8000"

  frontend:
    container_name: foodgram-frontend
    build: ./frontend
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static_volume:/staticfiles

  gateway:
    image: nginx:1.22.1
    container_name: foodgram-proxy
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
      - media_volume:/media
      - static_volume:/staticfiles
    depends_on:
      - backend
      - frontend
