version: '3.8'

volumes:
  pg_data:
  media_volume:
  static_volume:

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: jurassicon/foodgram_backend
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
    ports:
      - "8000:8000"
    command: >
      sh -c "until nc -z $DB_HOST $DB_PORT; do
            echo 'Waiting for Postgresâ€¦';
            sleep 1;
          done &&
          python manage.py migrate &&
          python recipes/scripts/import_data.py &&
          exec gunicorn --bind 0.0.0.0:8000 config.wsgi:application"

  frontend:
    image: jurassicon/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  gateway:
    image: jurassicon/foodgram_gateway
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/custom.conf
      - ./frontend/build:/usr/share/nginx/html
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/etc/nginx/html/static/
      - media_volume:/etc/nginx/html/media/
