volumes:
  pg_data:
  media_volume:
  static_volume:

services:
  frontend:
    image: jurassicon/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
  db:
    image: postgres:14-alpine
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: jurassicon/foodgram_backend
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/

  gateway:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/etc/nginx/html/static/
      - media_volume:/etc/nginx/html/media/
