version: '3.8'

volumes:
  pg_data:
  media_volume:
  static_volume:
  frontend_build:

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U", "${POSTGRES_USER}",
          "-d", "${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: jurassicon/foodgram_backend
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_volume:/app/media/
      - static_volume:/app/static/
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --no-input &&
        python recipes/scripts/import_data.py &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "

  frontend:
    image: jurassicon/foodgram_frontend
    restart: always
    volumes:
      - frontend_build:/app/build

  gateway:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_volume:/etc/nginx/html/static/
      - media_volume:/etc/nginx/html/media/
